swagger: "2.0"
info:
  description: " "
  version: "1.0.0"
  title: "test technique mms consulting"
  termsOfService: ""
paths:
  /api/commande/list:
    get:
      tags:
      - "commande"
      summary: "Afficher la liste des commandes"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "liste afficher avec succes"
  /api/commande/ajouter:
    post:
      tags:
      - "commande"
      summary: "ajouter une commande"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "l'objet commande qui va etre ajouter"
        required: true
        schema:
          $ref: "#/definitions/Commande"
      responses:
        "200":
          description: "commande ajouter avec succes"
  /api/commande/edit:
    put:
      tags:
      - "commande"
      summary: "modifier une commande"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "l'objet commande qui va etre modifier"
        required: true
      
        schema:
          $ref: "#/definitions/Produit"
      responses:
        "200":
          description: "successful operation"
  /api/commande/delete/{num}:
    delete:
      tags:
      - "commande"
      summary: "Deletes a pet"
      description: ""
      operationId: "deletePet"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "num"
        in: "path"
        description: "numero de commande à supprimer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
  /api/produit/getAll:
    get:
      tags:
      - "produit"
      summary: "affiche la liste des produit"
      description: "Returns a map of status codes to quantities"
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
    

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Commande:
    type: "object"
    properties:
      numero:
        type: "string"
        format: "string"
      date:
        type: "string"
        format: "date"
      prixTotal:
        type: "number"
        format: "BigDecimal"
      etat:
        type: "integer"
        format: "Long"
    xml:
      name: "Commande"
  Produit:
    type: "object"
    properties:
      code:
        type: "string"
        format: "string"
      marque:
        type: "string"
      modele:
        type: "string"
      caracteristiques:
        type: "string"
      quantite:
        type: "integer"
        format: "Long"
    xml:
      name: "Produit"
  Client:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int64"
      nom:
        type: "string"
      prenom:
        type: "string"
      adresse:
        type: "string"
      email:
        type: "string"
      gsm:
        type: "string"
      tel:
        type: "string"
    xml:
      name: "Client"
  LigneCommande:
    type: "object"
    properties:
      qte:
        type: "integer"
        format: "Long"
      prixUnitaire:
        type: "number"
      prixTotal:
        type: "number"
      etat:
        type: "number"
    xml:
      name: "Tag"
  category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      code:
        type: "string"
      libelle:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"